version: '3'

services:

  data_ingest:
    build:
      context: ./data_ingest
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python ingest_data.py

  data_processing:
    build:
      context: ./data_processing
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python process_data.py

  model_training:
    build:
      context: ./model_training
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python train_model.py

  model_serving:
    build:
      context: ./model_serving
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

  mlflow_tracking:
    build:
      context: ./mlflow_tracking
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python mlflow_server.py
    ports:
      - 5000:5000

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: pytest tests
