name: census_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - scikit-learn=0.24.1
  - pandas=1.2.3
  - numpy=1.24.3
  - pytest=6.2.2
  - fastapi=0.63.0
  - pip
  - pip:
    - -r file:requirements.txt
