name: Docker Compose CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and run the Docker Compose configuration
      run: |
        docker-compose build
        docker-compose up -d
    - name: Run flake8
      run: docker-compose run --rm <service-name> flake8 .
    - name: Run Pyre
      run: docker-compose run --rm <service-name> pyre check
    - name: Run pytest with coverage
      run: docker-compose run --rm <service-name> pytest --cov=. --cov-fail-under=90
    - name: Stop and remove containers
      run: docker-compose down
