name: Docker Compose CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and run the Docker Compose configuration
      run: |
        docker-compose build
        docker-compose up -d
        
    - name: Run flake8
      run: |
        for service in ${{ steps.config.outputs.services }}; do
          docker-compose exec $service flake8 .
        done
    
    - name: Run Pyre
      run: |
        for service in ${{ steps.config.outputs.services }}; do
          docker-compose exec $service pyre check
        done

    - name: Run Pytest
      run: |
        for service in ${{ steps.config.outputs.services }}; do
          docker-compose exec $service pytest --cov=. --cov-fail-under=90
        done
        
    - name: Stop and remove containers
      run: docker-compose down
