name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-cov mypy
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Type check with mypy
      run: |
        mypy --ignore-missing-imports .
    - name: Test with pytest
      run: |
        pytest ./starter/tests --ignore=./starter/tests/test_main.py --cov=./starter/src
