name: Docker Compose CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and run the Docker Compose configuration
      run: |
        docker-compose build
        docker-compose up -d

    - name: Run flake8
      run: docker-compose run --rm data_ingest data_processing model_training model_serving mlflow_tracking flake8 .

    - name: Run Pyre
      run: docker-compose run --rm data_ingest data_processing model_training model_serving mlflow_tracking pyre check

    - name: Run pytest with coverage
      run: docker-compose run --rm data_ingest data_processing model_training model_serving mlflow_tracking pytest --cov=. --cov-fail-under=90

    - name: Stop and remove containers
      run: docker-compose down
