name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        activate-environment: census_env
        environment-file: environment.yml
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        mamba install flake8 pytest pytest-cov mypy
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8 . --count --show-source --statistics
    - name: Type check with mypy
      shell: bash -l {0}
      run: |
        mypy --ignore-missing-imports .
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest --cov=.
    - name: Validate coverage
      shell: bash -l {0}
      run: |
        coverage report -m --fail-under=90
