name: Docker Compose CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull base image
      run: docker pull choya/my-base-image:latest
    
    - name: Build and run the Docker Compose configuration
      run: |
        docker-compose build
        docker-compose up -d

    - name: Run flake8
      run: docker-compose run --rm <service-name> flake8 .

    - name: Run Pyre
      run: docker-compose run --rm <service-name> pyre check

    - name: Run pytest with coverage
      run: docker-compose run --rm <service-name> pytest --cov=. --cov-fail-under=90

    - name: Stop and remove containers
      run: docker-compose down
